"""empty message

Revision ID: 601e9367ad48
Revises: f323256ad97d
Create Date: 2024-11-17 14:46:04.729530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601e9367ad48'
down_revision = 'f323256ad97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
