"""empty message

Revision ID: 77ad50835217
Revises: 601e9367ad48
Create Date: 2024-11-19 09:31:56.939162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ad50835217'
down_revision = '601e9367ad48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('quest_giver', sa.String(length=64), nullable=True),
    sa.Column('reward', sa.String(length=256), nullable=True),
    sa.Column('short_description', sa.String(length=128), nullable=False),
    sa.Column('long_description', sa.String(length=1028), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adventure_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adventure_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.drop_index('ix_quest_campaign_id')
        batch_op.drop_index('ix_quest_owner_id')

    op.drop_table('quest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('quest_giver', sa.VARCHAR(length=64), nullable=True),
    sa.Column('reward', sa.VARCHAR(length=256), nullable=True),
    sa.Column('short_description', sa.VARCHAR(length=128), nullable=False),
    sa.Column('long_description', sa.VARCHAR(length=1028), nullable=True),
    sa.Column('language', sa.VARCHAR(length=5), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest', schema=None) as batch_op:
        batch_op.create_index('ix_quest_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('ix_quest_campaign_id', ['campaign_id'], unique=False)

    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adventure_owner_id'))
        batch_op.drop_index(batch_op.f('ix_adventure_campaign_id'))

    op.drop_table('adventure')
    # ### end Alembic commands ###
