"""empty message

Revision ID: ee32c8be4ffa
Revises: 
Create Date: 2024-12-14 15:43:58.197762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee32c8be4ffa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('asset_type', sa.Enum('setting', 'campaign', 'adventure', 'city', 'encounter', 'kingdom', 'point_of_interest', 'creature', 'spell', 'item', 'feat', name='assettypes'), nullable=False),
    sa.Column('short_description', sa.String(length=256), nullable=False),
    sa.Column('long_description', sa.String(length=1028), nullable=True),
    sa.Column('geography_description', sa.String(length=256), nullable=True),
    sa.Column('demographics_description', sa.String(length=256), nullable=True),
    sa.Column('political_description', sa.String(length=256), nullable=True),
    sa.Column('economy_description', sa.String(length=256), nullable=True),
    sa.Column('history_description', sa.String(length=256), nullable=True),
    sa.Column('gm_notes', sa.String(length=2000), nullable=True),
    sa.Column('ruler', sa.String(length=128), nullable=True),
    sa.Column('diety_name', sa.String(length=64), nullable=False),
    sa.Column('symbol_description', sa.String(length=128), nullable=True),
    sa.Column('quest_giver', sa.String(length=64), nullable=True),
    sa.Column('reward', sa.String(length=256), nullable=True),
    sa.Column('challenge_rating', sa.Float(), nullable=True),
    sa.Column('loot', sa.String(length=512), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('kingdom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['kingdom_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_kingdom_id'), ['kingdom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_setting_id'), ['setting_id'], unique=False)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('players', sa.String(length=256), nullable=True),
    sa.Column('short_description', sa.String(length=128), nullable=False),
    sa.Column('long_description', sa.String(length=1028), nullable=True),
    sa.Column('game_master_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_master_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_game_master_id'), ['game_master_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_game_master_id'))

    op.drop_table('session')
    op.drop_table('followers')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_setting_id'))
        batch_op.drop_index(batch_op.f('ix_asset_owner_id'))
        batch_op.drop_index(batch_op.f('ix_asset_kingdom_id'))
        batch_op.drop_index(batch_op.f('ix_asset_campaign_id'))

    op.drop_table('asset')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
